name: build-publish-tag

on:
  push:
    branches: [ "!*" ]
    tags: [ '*' ]
    
concurrency: master
    
env:
  REPOSITORY: morecontainers/awscli

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Get version tag
      id: tag
      run: |
        [[ ! "$GITHUB_REF" =~ refs/tags ]] && exit
        echo "::set-output name=value::${GITHUB_REF#refs/tags/}"
    - run: docker login -u ${{ secrets.HUB_DOCKER_USERNAME }} -p ${{ secrets.HUB_DOCKER_PASSWORD }}
    - run: docker buildx build --tag $REPOSITORY:${{ steps.tag.outputs.value }} .
    - run: docker push $REPOSITORY:${{ steps.tag.outputs.value }}
