on:
  push:
    branches: [ "!*" ]
    tags: [ '*' ]
    
concurrency: master
    
env:
  REPOSITORY: morecontainers/awscli

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: docker login -u ${{ secrets.HUB_DOCKER_USERNAME }} -p ${{ secrets.HUB_DOCKER_PASSWORD }}
    - run: echo "::set-env name=TAG::$(git tag --points-at HEAD)"
    - run: docker build --tag $REPOSITORY:$TAG .
    - run: docker push $REPOSITORY:$TAG
